spring:
  application:
    name: core-service
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/blps}
    username: ${DATABASE_USERNAME:blps}
    password: ${DATABASE_PASSWORD:blps}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: false
      open-in-view: false
      properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: core-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
app:
  kafka:
    payment-topic: ${PAYMENT_REQUESTS_TOPIC:payment-requests}
  payment-reminders:
    fixed-delay-ms: ${PAYMENT_REMINDER_SCHEDULER_DELAY_MS:30000}
    payment-url-assigned-topic: ${PAYMENT_URL_ASSIGNED_TOPIC:payment-url-assigned}
erpnext:
  company: ${ERPNEXT_COMPANY:AirBNB}
  service-item-code: ${ERPNEXT_SERVICE_ITEM_CODE:EXTRA_SERVICE}
  jndi-name: ${ERPNEXT_JNDI_NAME:java:/eis/ErpNextCF}
server:
  port: 8433
